{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "hawaiian-vector",
   "metadata": {},
   "outputs": [],
   "source": [
    "text = \"\"\"\n",
    "Wikipedia (/ˌwɪkɪˈpiːdiə/ (About this soundlisten) wik-ih-PEE-dee-ə or /ˌwɪki-/ (About this soundlisten) wik-ee-) is a free, multilingual open-collaborative online encyclopedia created and maintained by a community of volunteer contributors using a wiki-based editing system. Wikipedia is the largest general reference work on the Internet,[3] and one of the 15 most popular websites as ranked by Alexa; in 2021, it was ranked as the 13th most visited.[4][note 3] The project carries no advertisements and is hosted by the Wikimedia Foundation, an American non-profit organization funded mainly through donations, 80% of which are small donations from individual users.[6]\n",
    "\n",
    "Wikipedia was launched on January 15, 2001, by Jimmy Wales and Larry Sanger; its name was coined as a portmanteau of \"wiki\" and \"encyclopedia\". Initially available only in English, versions in other languages were quickly developed. The English Wikipedia, with 6.3 million articles as of March 2021, is the largest of the 319 language editions. Combined, Wikipedia's editions comprise more than 55 million articles, and attract more than 17 million edits and more than 1.7 billion unique visitors per month.[7]\n",
    "\n",
    "Wikipedia has been criticized for its uneven accuracy and for exhibiting systemic bias, particularly gender bias, with the majority of editors being male.[8] In 2006, Time magazine stated that the open-door policy of allowing anyone to edit had made Wikipedia the \"biggest and perhaps the best encyclopedia in the world\", and a testament to the vision of Jimmy Wales.[9] The project's reputation improved further in the 2010s, as it received praise for its unique structure, culture, and absence of commercial bias.[3][8] In 2018, Facebook and YouTube announced that they would help users detect fake news by suggesting links to related Wikipedia articles.[10]\n",
    "\"\"\" "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "inner-turning",
   "metadata": {},
   "outputs": [],
   "source": [
    "import spacy\n",
    "from spacy.lang.en.stop_words import STOP_WORDS\n",
    "from string import punctuation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "developing-vermont",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['her',\n",
       " 'they',\n",
       " 'see',\n",
       " 'together',\n",
       " \"n't\",\n",
       " 'show',\n",
       " 'an',\n",
       " 'part',\n",
       " 'who',\n",
       " '‘s',\n",
       " 'regarding',\n",
       " 'forty',\n",
       " 'seemed',\n",
       " 'are',\n",
       " 'will',\n",
       " 'along',\n",
       " 'toward',\n",
       " 'does',\n",
       " \"'ll\",\n",
       " 'several',\n",
       " '’re',\n",
       " 'them',\n",
       " 'else',\n",
       " 'full',\n",
       " 'hence',\n",
       " 'whereas',\n",
       " 'otherwise',\n",
       " 'indeed',\n",
       " 'themselves',\n",
       " 'whither',\n",
       " 'below',\n",
       " 'beyond',\n",
       " 'seem',\n",
       " 'whose',\n",
       " 'six',\n",
       " 'therefore',\n",
       " 'give',\n",
       " 'to',\n",
       " 'again',\n",
       " 'wherever',\n",
       " 'on',\n",
       " 'himself',\n",
       " 'become',\n",
       " 'therein',\n",
       " 'across',\n",
       " 'your',\n",
       " 'until',\n",
       " 'into',\n",
       " 'would',\n",
       " 'go',\n",
       " 'done',\n",
       " 'often',\n",
       " 'whereafter',\n",
       " 'herein',\n",
       " 'nine',\n",
       " 'except',\n",
       " 'his',\n",
       " 'however',\n",
       " 'seems',\n",
       " 'already',\n",
       " 'five',\n",
       " 'been',\n",
       " 'hers',\n",
       " 'most',\n",
       " 'any',\n",
       " 'formerly',\n",
       " 'other',\n",
       " 'during',\n",
       " 'quite',\n",
       " 'i',\n",
       " 'top',\n",
       " 'besides',\n",
       " 'being',\n",
       " 'through',\n",
       " 'n’t',\n",
       " 'none',\n",
       " 'much',\n",
       " '’ve',\n",
       " 'no',\n",
       " 'here',\n",
       " 'only',\n",
       " 'unless',\n",
       " 'empty',\n",
       " 'can',\n",
       " 'bottom',\n",
       " 'such',\n",
       " 'using',\n",
       " 'these',\n",
       " 'nothing',\n",
       " 'whole',\n",
       " 'under',\n",
       " 'back',\n",
       " 'sometime',\n",
       " 'many',\n",
       " 'last',\n",
       " 'off',\n",
       " 'alone',\n",
       " 'herself',\n",
       " 'those',\n",
       " 'may',\n",
       " 'throughout',\n",
       " 'from',\n",
       " 'front',\n",
       " 'is',\n",
       " 'sometimes',\n",
       " 'while',\n",
       " 'then',\n",
       " 'least',\n",
       " 'down',\n",
       " 'eight',\n",
       " 'meanwhile',\n",
       " 'onto',\n",
       " 'everything',\n",
       " 'am',\n",
       " 'hereby',\n",
       " 'so',\n",
       " 'neither',\n",
       " 'becoming',\n",
       " 'sixty',\n",
       " 'than',\n",
       " 'always',\n",
       " 'their',\n",
       " 'used',\n",
       " 'enough',\n",
       " 'myself',\n",
       " 'twelve',\n",
       " 'around',\n",
       " 'our',\n",
       " 'nevertheless',\n",
       " 'please',\n",
       " 'name',\n",
       " 'do',\n",
       " 'afterwards',\n",
       " 'now',\n",
       " 'whenever',\n",
       " 'something',\n",
       " 'which',\n",
       " 'should',\n",
       " 'over',\n",
       " 'four',\n",
       " 'everyone',\n",
       " 'yourself',\n",
       " 'among',\n",
       " 'she',\n",
       " 'put',\n",
       " 'in',\n",
       " 'former',\n",
       " 're',\n",
       " 'towards',\n",
       " 'one',\n",
       " 'next',\n",
       " 'hundred',\n",
       " 'were',\n",
       " 'all',\n",
       " 'within',\n",
       " 'me',\n",
       " 'anywhere',\n",
       " 'was',\n",
       " 'it',\n",
       " 'really',\n",
       " 'own',\n",
       " 'him',\n",
       " '‘m',\n",
       " 'before',\n",
       " \"'re\",\n",
       " \"'s\",\n",
       " 'rather',\n",
       " 'because',\n",
       " 'between',\n",
       " 'somehow',\n",
       " 'due',\n",
       " 'against',\n",
       " 'thereupon',\n",
       " 'never',\n",
       " 'side',\n",
       " 'be',\n",
       " 'just',\n",
       " 'everywhere',\n",
       " 'doing',\n",
       " 'its',\n",
       " 'once',\n",
       " 'every',\n",
       " 'amount',\n",
       " '‘d',\n",
       " 'after',\n",
       " 'various',\n",
       " '’d',\n",
       " 'what',\n",
       " 'beside',\n",
       " 'above',\n",
       " 'hereupon',\n",
       " 'fifty',\n",
       " 'amongst',\n",
       " 'latter',\n",
       " 'via',\n",
       " 'too',\n",
       " 'eleven',\n",
       " '’s',\n",
       " 'made',\n",
       " 'we',\n",
       " 'there',\n",
       " '’ll',\n",
       " 'elsewhere',\n",
       " 'also',\n",
       " 'cannot',\n",
       " 'ca',\n",
       " 'by',\n",
       " 'less',\n",
       " 'ourselves',\n",
       " 'whom',\n",
       " 'somewhere',\n",
       " 'mostly',\n",
       " 'though',\n",
       " 'get',\n",
       " 'about',\n",
       " 'how',\n",
       " 'out',\n",
       " 'still',\n",
       " 'fifteen',\n",
       " 'my',\n",
       " 'whereby',\n",
       " '‘ve',\n",
       " 'call',\n",
       " 'mine',\n",
       " 'keep',\n",
       " \"'ve\",\n",
       " 'itself',\n",
       " 'could',\n",
       " 'some',\n",
       " 'why',\n",
       " 'others',\n",
       " 'and',\n",
       " 'well',\n",
       " 'thence',\n",
       " 'the',\n",
       " 'where',\n",
       " 'although',\n",
       " 'serious',\n",
       " 'noone',\n",
       " 'yet',\n",
       " 'twenty',\n",
       " 'for',\n",
       " '’m',\n",
       " 'had',\n",
       " 'yours',\n",
       " 'at',\n",
       " 'he',\n",
       " 'since',\n",
       " 'even',\n",
       " 'few',\n",
       " 'very',\n",
       " 'n‘t',\n",
       " 'thereafter',\n",
       " 'both',\n",
       " 'say',\n",
       " 'became',\n",
       " 'without',\n",
       " 'ten',\n",
       " 'third',\n",
       " 'thereby',\n",
       " '‘re',\n",
       " 'of',\n",
       " 'did',\n",
       " 'has',\n",
       " 'moreover',\n",
       " 'if',\n",
       " \"'m\",\n",
       " 'anything',\n",
       " 'make',\n",
       " 'yourselves',\n",
       " \"'d\",\n",
       " 'wherein',\n",
       " 'up',\n",
       " 'whence',\n",
       " 'thru',\n",
       " 'three',\n",
       " 'this',\n",
       " 'not',\n",
       " 'with',\n",
       " 'hereafter',\n",
       " 'whether',\n",
       " 'us',\n",
       " 'latterly',\n",
       " 'whereupon',\n",
       " 'anyone',\n",
       " 'further',\n",
       " 'first',\n",
       " 'behind',\n",
       " 'beforehand',\n",
       " 'whoever',\n",
       " 'almost',\n",
       " 'you',\n",
       " 'per',\n",
       " 'two',\n",
       " 'must',\n",
       " 'each',\n",
       " 'another',\n",
       " 'namely',\n",
       " 'either',\n",
       " 'anyway',\n",
       " 'nowhere',\n",
       " 'ever',\n",
       " 'perhaps',\n",
       " '‘ll',\n",
       " 'when',\n",
       " 'take',\n",
       " 'as',\n",
       " 'seeming',\n",
       " 'that',\n",
       " 'more',\n",
       " 'ours',\n",
       " 'a',\n",
       " 'becomes',\n",
       " 'whatever',\n",
       " 'nor',\n",
       " 'anyhow',\n",
       " 'someone',\n",
       " 'upon',\n",
       " 'but',\n",
       " 'move',\n",
       " 'or',\n",
       " 'thus',\n",
       " 'nobody',\n",
       " 'have',\n",
       " 'same',\n",
       " 'might']"
      ]
     },
     "execution_count": 48,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "stopwords = list(STOP_WORDS)\n",
    "stopwords"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "id": "organizational-peace",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<spacy.lang.en.English at 0x241aa7ef130>"
      ]
     },
     "execution_count": 49,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "nlp = spacy.load('en_core_web_sm') \n",
    "nlp"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "planned-jumping",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "\n",
       "Wikipedia (/ˌwɪkɪˈpiːdiə/ (About this soundlisten) wik-ih-PEE-dee-ə or /ˌwɪki-/ (About this soundlisten) wik-ee-) is a free, multilingual open-collaborative online encyclopedia created and maintained by a community of volunteer contributors using a wiki-based editing system. Wikipedia is the largest general reference work on the Internet,[3] and one of the 15 most popular websites as ranked by Alexa; in 2021, it was ranked as the 13th most visited.[4][note 3] The project carries no advertisements and is hosted by the Wikimedia Foundation, an American non-profit organization funded mainly through donations, 80% of which are small donations from individual users.[6]\n",
       "\n",
       "Wikipedia was launched on January 15, 2001, by Jimmy Wales and Larry Sanger; its name was coined as a portmanteau of \"wiki\" and \"encyclopedia\". Initially available only in English, versions in other languages were quickly developed. The English Wikipedia, with 6.3 million articles as of March 2021, is the largest of the 319 language editions. Combined, Wikipedia's editions comprise more than 55 million articles, and attract more than 17 million edits and more than 1.7 billion unique visitors per month.[7]\n",
       "\n",
       "Wikipedia has been criticized for its uneven accuracy and for exhibiting systemic bias, particularly gender bias, with the majority of editors being male.[8] In 2006, Time magazine stated that the open-door policy of allowing anyone to edit had made Wikipedia the \"biggest and perhaps the best encyclopedia in the world\", and a testament to the vision of Jimmy Wales.[9] The project's reputation improved further in the 2010s, as it received praise for its unique structure, culture, and absence of commercial bias.[3][8] In 2018, Facebook and YouTube announced that they would help users detect fake news by suggesting links to related Wikipedia articles.[10]"
      ]
     },
     "execution_count": 50,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "doc = nlp(text)\n",
    "doc"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "id": "blond-asbestos",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['\\n', 'Wikipedia', '(', '/ˌwɪkɪˈpiːdiə/', '(', 'About', 'this', 'soundlisten', ')', 'wik', '-', 'ih', '-', 'PEE', '-', 'dee', '-', 'ə', 'or', '/ˌwɪki-/', '(', 'About', 'this', 'soundlisten', ')', 'wik', '-', 'ee-', ')', 'is', 'a', 'free', ',', 'multilingual', 'open', '-', 'collaborative', 'online', 'encyclopedia', 'created', 'and', 'maintained', 'by', 'a', 'community', 'of', 'volunteer', 'contributors', 'using', 'a', 'wiki', '-', 'based', 'editing', 'system', '.', 'Wikipedia', 'is', 'the', 'largest', 'general', 'reference', 'work', 'on', 'the', 'Internet,[3', ']', 'and', 'one', 'of', 'the', '15', 'most', 'popular', 'websites', 'as', 'ranked', 'by', 'Alexa', ';', 'in', '2021', ',', 'it', 'was', 'ranked', 'as', 'the', '13th', 'most', 'visited.[4][note', '3', ']', 'The', 'project', 'carries', 'no', 'advertisements', 'and', 'is', 'hosted', 'by', 'the', 'Wikimedia', 'Foundation', ',', 'an', 'American', 'non', '-', 'profit', 'organization', 'funded', 'mainly', 'through', 'donations', ',', '80', '%', 'of', 'which', 'are', 'small', 'donations', 'from', 'individual', 'users.[6', ']', '\\n\\n', 'Wikipedia', 'was', 'launched', 'on', 'January', '15', ',', '2001', ',', 'by', 'Jimmy', 'Wales', 'and', 'Larry', 'Sanger', ';', 'its', 'name', 'was', 'coined', 'as', 'a', 'portmanteau', 'of', '\"', 'wiki', '\"', 'and', '\"', 'encyclopedia', '\"', '.', 'Initially', 'available', 'only', 'in', 'English', ',', 'versions', 'in', 'other', 'languages', 'were', 'quickly', 'developed', '.', 'The', 'English', 'Wikipedia', ',', 'with', '6.3', 'million', 'articles', 'as', 'of', 'March', '2021', ',', 'is', 'the', 'largest', 'of', 'the', '319', 'language', 'editions', '.', 'Combined', ',', 'Wikipedia', \"'s\", 'editions', 'comprise', 'more', 'than', '55', 'million', 'articles', ',', 'and', 'attract', 'more', 'than', '17', 'million', 'edits', 'and', 'more', 'than', '1.7', 'billion', 'unique', 'visitors', 'per', 'month.[7', ']', '\\n\\n', 'Wikipedia', 'has', 'been', 'criticized', 'for', 'its', 'uneven', 'accuracy', 'and', 'for', 'exhibiting', 'systemic', 'bias', ',', 'particularly', 'gender', 'bias', ',', 'with', 'the', 'majority', 'of', 'editors', 'being', 'male.[8', ']', 'In', '2006', ',', 'Time', 'magazine', 'stated', 'that', 'the', 'open', '-', 'door', 'policy', 'of', 'allowing', 'anyone', 'to', 'edit', 'had', 'made', 'Wikipedia', 'the', '\"', 'biggest', 'and', 'perhaps', 'the', 'best', 'encyclopedia', 'in', 'the', 'world', '\"', ',', 'and', 'a', 'testament', 'to', 'the', 'vision', 'of', 'Jimmy', 'Wales.[9', ']', 'The', 'project', \"'s\", 'reputation', 'improved', 'further', 'in', 'the', '2010s', ',', 'as', 'it', 'received', 'praise', 'for', 'its', 'unique', 'structure', ',', 'culture', ',', 'and', 'absence', 'of', 'commercial', 'bias.[3][8', ']', 'In', '2018', ',', 'Facebook', 'and', 'YouTube', 'announced', 'that', 'they', 'would', 'help', 'users', 'detect', 'fake', 'news', 'by', 'suggesting', 'links', 'to', 'related', 'Wikipedia', 'articles.[10', ']', '\\n']\n"
     ]
    }
   ],
   "source": [
    "tokens = [token.text for token in doc]\n",
    "print(tokens)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "id": "quiet-memorial",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'!\"#$%&\\'()*+,-./:;<=>?@[\\\\]^_`{|}~\\n'"
      ]
     },
     "execution_count": 52,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "punctuation = punctuation + '\\n'\n",
    "punctuation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "id": "toxic-marketing",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'Wikipedia': 8, '/ˌwɪkɪˈpiːdiə/': 1, 'soundlisten': 2, 'wik': 2, 'ih': 1, 'PEE': 1, 'dee': 1, 'ə': 1, '/ˌwɪki-/': 1, 'ee-': 1, 'free': 1, 'multilingual': 1, 'open': 2, 'collaborative': 1, 'online': 1, 'encyclopedia': 3, 'created': 1, 'maintained': 1, 'community': 1, 'volunteer': 1, 'contributors': 1, 'wiki': 2, 'based': 1, 'editing': 1, 'system': 1, 'largest': 2, 'general': 1, 'reference': 1, 'work': 1, 'Internet,[3': 1, '15': 2, 'popular': 1, 'websites': 1, 'ranked': 2, 'Alexa': 1, '2021': 2, '13th': 1, 'visited.[4][note': 1, '3': 1, 'project': 2, 'carries': 1, 'advertisements': 1, 'hosted': 1, 'Wikimedia': 1, 'Foundation': 1, 'American': 1, 'non': 1, 'profit': 1, 'organization': 1, 'funded': 1, 'mainly': 1, 'donations': 2, '80': 1, 'small': 1, 'individual': 1, 'users.[6': 1, '\\n\\n': 2, 'launched': 1, 'January': 1, '2001': 1, 'Jimmy': 2, 'Wales': 1, 'Larry': 1, 'Sanger': 1, 'coined': 1, 'portmanteau': 1, 'Initially': 1, 'available': 1, 'English': 2, 'versions': 1, 'languages': 1, 'quickly': 1, 'developed': 1, '6.3': 1, 'million': 3, 'articles': 2, 'March': 1, '319': 1, 'language': 1, 'editions': 2, 'Combined': 1, 'comprise': 1, '55': 1, 'attract': 1, '17': 1, 'edits': 1, '1.7': 1, 'billion': 1, 'unique': 2, 'visitors': 1, 'month.[7': 1, 'criticized': 1, 'uneven': 1, 'accuracy': 1, 'exhibiting': 1, 'systemic': 1, 'bias': 2, 'particularly': 1, 'gender': 1, 'majority': 1, 'editors': 1, 'male.[8': 1, '2006': 1, 'Time': 1, 'magazine': 1, 'stated': 1, 'door': 1, 'policy': 1, 'allowing': 1, 'edit': 1, 'biggest': 1, 'best': 1, 'world': 1, 'testament': 1, 'vision': 1, 'Wales.[9': 1, 'reputation': 1, 'improved': 1, '2010s': 1, 'received': 1, 'praise': 1, 'structure': 1, 'culture': 1, 'absence': 1, 'commercial': 1, 'bias.[3][8': 1, '2018': 1, 'Facebook': 1, 'YouTube': 1, 'announced': 1, 'help': 1, 'users': 1, 'detect': 1, 'fake': 1, 'news': 1, 'suggesting': 1, 'links': 1, 'related': 1, 'articles.[10': 1}\n"
     ]
    }
   ],
   "source": [
    "word_frequencies = {}\n",
    "for word in doc:\n",
    "    if word.text.lower() not in stopwords:\n",
    "        if word.text.lower() not in punctuation:\n",
    "            if word.text not in word_frequencies.keys():\n",
    "                word_frequencies[word.text] = 1\n",
    "            else: \n",
    "                word_frequencies[word.text] += 1\n",
    "                \n",
    "print(word_frequencies)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "id": "novel-drinking",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "8"
      ]
     },
     "execution_count": 54,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "max_frequency = max(word_frequencies.values())\n",
    "max_frequency"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "id": "bacterial-tucson",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'Wikipedia': 1.0, '/ˌwɪkɪˈpiːdiə/': 0.125, 'soundlisten': 0.25, 'wik': 0.25, 'ih': 0.125, 'PEE': 0.125, 'dee': 0.125, 'ə': 0.125, '/ˌwɪki-/': 0.125, 'ee-': 0.125, 'free': 0.125, 'multilingual': 0.125, 'open': 0.25, 'collaborative': 0.125, 'online': 0.125, 'encyclopedia': 0.375, 'created': 0.125, 'maintained': 0.125, 'community': 0.125, 'volunteer': 0.125, 'contributors': 0.125, 'wiki': 0.25, 'based': 0.125, 'editing': 0.125, 'system': 0.125, 'largest': 0.25, 'general': 0.125, 'reference': 0.125, 'work': 0.125, 'Internet,[3': 0.125, '15': 0.25, 'popular': 0.125, 'websites': 0.125, 'ranked': 0.25, 'Alexa': 0.125, '2021': 0.25, '13th': 0.125, 'visited.[4][note': 0.125, '3': 0.125, 'project': 0.25, 'carries': 0.125, 'advertisements': 0.125, 'hosted': 0.125, 'Wikimedia': 0.125, 'Foundation': 0.125, 'American': 0.125, 'non': 0.125, 'profit': 0.125, 'organization': 0.125, 'funded': 0.125, 'mainly': 0.125, 'donations': 0.25, '80': 0.125, 'small': 0.125, 'individual': 0.125, 'users.[6': 0.125, '\\n\\n': 0.25, 'launched': 0.125, 'January': 0.125, '2001': 0.125, 'Jimmy': 0.25, 'Wales': 0.125, 'Larry': 0.125, 'Sanger': 0.125, 'coined': 0.125, 'portmanteau': 0.125, 'Initially': 0.125, 'available': 0.125, 'English': 0.25, 'versions': 0.125, 'languages': 0.125, 'quickly': 0.125, 'developed': 0.125, '6.3': 0.125, 'million': 0.375, 'articles': 0.25, 'March': 0.125, '319': 0.125, 'language': 0.125, 'editions': 0.25, 'Combined': 0.125, 'comprise': 0.125, '55': 0.125, 'attract': 0.125, '17': 0.125, 'edits': 0.125, '1.7': 0.125, 'billion': 0.125, 'unique': 0.25, 'visitors': 0.125, 'month.[7': 0.125, 'criticized': 0.125, 'uneven': 0.125, 'accuracy': 0.125, 'exhibiting': 0.125, 'systemic': 0.125, 'bias': 0.25, 'particularly': 0.125, 'gender': 0.125, 'majority': 0.125, 'editors': 0.125, 'male.[8': 0.125, '2006': 0.125, 'Time': 0.125, 'magazine': 0.125, 'stated': 0.125, 'door': 0.125, 'policy': 0.125, 'allowing': 0.125, 'edit': 0.125, 'biggest': 0.125, 'best': 0.125, 'world': 0.125, 'testament': 0.125, 'vision': 0.125, 'Wales.[9': 0.125, 'reputation': 0.125, 'improved': 0.125, '2010s': 0.125, 'received': 0.125, 'praise': 0.125, 'structure': 0.125, 'culture': 0.125, 'absence': 0.125, 'commercial': 0.125, 'bias.[3][8': 0.125, '2018': 0.125, 'Facebook': 0.125, 'YouTube': 0.125, 'announced': 0.125, 'help': 0.125, 'users': 0.125, 'detect': 0.125, 'fake': 0.125, 'news': 0.125, 'suggesting': 0.125, 'links': 0.125, 'related': 0.125, 'articles.[10': 0.125}\n"
     ]
    }
   ],
   "source": [
    "for word in word_frequencies.keys():\n",
    "    word_frequencies[word] = word_frequencies[word]/max_frequency\n",
    "\n",
    "print(word_frequencies) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "id": "civil-meditation",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[\n",
      "Wikipedia (/ˌwɪkɪˈpiːdiə/ (About this soundlisten) wik-ih-PEE-dee-ə or /ˌwɪki-/ (About this soundlisten) wik-ee-) is a free, multilingual open-collaborative online encyclopedia created and maintained by a community of volunteer contributors using a wiki-based editing system., Wikipedia is the largest general reference work on the Internet,[3] and one of the 15 most popular websites as ranked by Alexa; in 2021, it was ranked as the 13th most visited.[4][note 3] The project carries no advertisements and is hosted by the Wikimedia Foundation, an American non-profit organization funded mainly through donations, 80% of which are small donations from individual users.[6]\n",
      "\n",
      "Wikipedia was launched on January 15, 2001, by Jimmy Wales and Larry Sanger; its name was coined as a portmanteau of \"wiki\" and \"encyclopedia\"., Initially available only in English, versions in other languages were quickly developed., The English Wikipedia, with 6.3 million articles as of March 2021, is the largest of the 319 language editions., Combined, Wikipedia's editions comprise more than 55 million articles, and attract more than 17 million edits and more than 1.7 billion unique visitors per month.[7]\n",
      "\n",
      "Wikipedia has been criticized for its uneven accuracy and for exhibiting systemic bias, particularly gender bias, with the majority of editors being male.[8], In 2006, Time magazine stated that the open-door policy of allowing anyone to edit had made Wikipedia the \"biggest and perhaps the best encyclopedia in the world\", and a testament to the vision of Jimmy Wales.[9] The project's reputation improved further in the 2010s, as it received praise for its unique structure, culture, and absence of commercial bias.[3][8], In 2018, Facebook and YouTube announced that they would help users detect fake news by suggesting links to related Wikipedia articles.[10]\n",
      "]\n"
     ]
    }
   ],
   "source": [
    "sentence_tokens = [sent for sent in doc.sents]\n",
    "print(sentence_tokens)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "id": "utility-stretch",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{\n",
       " Wikipedia (/ˌwɪkɪˈpiːdiə/ (About this soundlisten) wik-ih-PEE-dee-ə or /ˌwɪki-/ (About this soundlisten) wik-ee-) is a free, multilingual open-collaborative online encyclopedia created and maintained by a community of volunteer contributors using a wiki-based editing system.: 4.125,\n",
       " Wikipedia is the largest general reference work on the Internet,[3] and one of the 15 most popular websites as ranked by Alexa; in 2021, it was ranked as the 13th most visited.[4][note 3] The project carries no advertisements and is hosted by the Wikimedia Foundation, an American non-profit organization funded mainly through donations, 80% of which are small donations from individual users.[6]\n",
       " \n",
       " Wikipedia was launched on January 15, 2001, by Jimmy Wales and Larry Sanger; its name was coined as a portmanteau of \"wiki\" and \"encyclopedia\".: 6.125,\n",
       " Initially available only in English, versions in other languages were quickly developed.: 0.625,\n",
       " The English Wikipedia, with 6.3 million articles as of March 2021, is the largest of the 319 language editions.: 1.75,\n",
       " Combined, Wikipedia's editions comprise more than 55 million articles, and attract more than 17 million edits and more than 1.7 billion unique visitors per month.[7]\n",
       " \n",
       " Wikipedia has been criticized for its uneven accuracy and for exhibiting systemic bias, particularly gender bias, with the majority of editors being male.[8]: 4.625,\n",
       " In 2006, Time magazine stated that the open-door policy of allowing anyone to edit had made Wikipedia the \"biggest and perhaps the best encyclopedia in the world\", and a testament to the vision of Jimmy Wales.[9] The project's reputation improved further in the 2010s, as it received praise for its unique structure, culture, and absence of commercial bias.[3][8]: 3.875,\n",
       " In 2018, Facebook and YouTube announced that they would help users detect fake news by suggesting links to related Wikipedia articles.[10]: 1.375}"
      ]
     },
     "execution_count": 57,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "sentence_scores = {}\n",
    "for sent in sentence_tokens:\n",
    "    for word in sent:\n",
    "        if word.text.lower() in word_frequencies.keys():\n",
    "            if sent not in sentence_scores.keys():\n",
    "                sentence_scores[sent] = word_frequencies[word.text.lower()]\n",
    "            else:\n",
    "                sentence_scores[sent] += word_frequencies[word.text.lower()]\n",
    "                \n",
    "sentence_scores"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 65,
   "id": "powerful-princess",
   "metadata": {},
   "outputs": [],
   "source": [
    "from heapq import nlargest"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "id": "literary-terminology",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "2"
      ]
     },
     "execution_count": 66,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "select_length = int(len(sentence_tokens)*0.3)\n",
    "select_length"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "id": "failing-calcium",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[Wikipedia is the largest general reference work on the Internet,[3] and one of the 15 most popular websites as ranked by Alexa; in 2021, it was ranked as the 13th most visited.[4][note 3] The project carries no advertisements and is hosted by the Wikimedia Foundation, an American non-profit organization funded mainly through donations, 80% of which are small donations from individual users.[6]\n",
       " \n",
       " Wikipedia was launched on January 15, 2001, by Jimmy Wales and Larry Sanger; its name was coined as a portmanteau of \"wiki\" and \"encyclopedia\".,\n",
       " Combined, Wikipedia's editions comprise more than 55 million articles, and attract more than 17 million edits and more than 1.7 billion unique visitors per month.[7]\n",
       " \n",
       " Wikipedia has been criticized for its uneven accuracy and for exhibiting systemic bias, particularly gender bias, with the majority of editors being male.[8]]"
      ]
     },
     "execution_count": 67,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "summary = nlargest(select_length, sentence_scores, key = sentence_scores.get)\n",
    "summary"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 68,
   "id": "satisfied-click",
   "metadata": {},
   "outputs": [],
   "source": [
    "final_summary = [word.text for word in summary]\n",
    "summary = ' '.join(final_summary) "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "id": "secure-philip",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Wikipedia (/ˌwɪkɪˈpiːdiə/ (About this soundlisten) wik-ih-PEE-dee-ə or /ˌwɪki-/ (About this soundlisten) wik-ee-) is a free, multilingual open-collaborative online encyclopedia created and maintained by a community of volunteer contributors using a wiki-based editing system. Wikipedia is the largest general reference work on the Internet,[3] and one of the 15 most popular websites as ranked by Alexa; in 2021, it was ranked as the 13th most visited.[4][note 3] The project carries no advertisements and is hosted by the Wikimedia Foundation, an American non-profit organization funded mainly through donations, 80% of which are small donations from individual users.[6]\n",
      "\n",
      "Wikipedia was launched on January 15, 2001, by Jimmy Wales and Larry Sanger; its name was coined as a portmanteau of \"wiki\" and \"encyclopedia\". Initially available only in English, versions in other languages were quickly developed. The English Wikipedia, with 6.3 million articles as of March 2021, is the largest of the 319 language editions. Combined, Wikipedia's editions comprise more than 55 million articles, and attract more than 17 million edits and more than 1.7 billion unique visitors per month.[7]\n",
      "\n",
      "Wikipedia has been criticized for its uneven accuracy and for exhibiting systemic bias, particularly gender bias, with the majority of editors being male.[8] In 2006, Time magazine stated that the open-door policy of allowing anyone to edit had made Wikipedia the \"biggest and perhaps the best encyclopedia in the world\", and a testament to the vision of Jimmy Wales.[9] The project's reputation improved further in the 2010s, as it received praise for its unique structure, culture, and absence of commercial bias.[3][8] In 2018, Facebook and YouTube announced that they would help users detect fake news by suggesting links to related Wikipedia articles.[10]\n",
      "\n"
     ]
    }
   ],
   "source": [
    "print(text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 70,
   "id": "faced-apartment",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Wikipedia is the largest general reference work on the Internet,[3] and one of the 15 most popular websites as ranked by Alexa; in 2021, it was ranked as the 13th most visited.[4][note 3] The project carries no advertisements and is hosted by the Wikimedia Foundation, an American non-profit organization funded mainly through donations, 80% of which are small donations from individual users.[6]\n",
      "\n",
      "Wikipedia was launched on January 15, 2001, by Jimmy Wales and Larry Sanger; its name was coined as a portmanteau of \"wiki\" and \"encyclopedia\". Combined, Wikipedia's editions comprise more than 55 million articles, and attract more than 17 million edits and more than 1.7 billion unique visitors per month.[7]\n",
      "\n",
      "Wikipedia has been criticized for its uneven accuracy and for exhibiting systemic bias, particularly gender bias, with the majority of editors being male.[8]\n"
     ]
    }
   ],
   "source": [
    "print(summary)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 71,
   "id": "seventh-auction",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(1848, 866)"
      ]
     },
     "execution_count": 71,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "Exception in callback BaseSelectorEventLoop._read_from_self()\n",
      "handle: <Handle BaseSelectorEventLoop._read_from_self()>\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\events.py\", line 81, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\Asus vivoBook\\Anaconda3\\envs\\tf\\lib\\asyncio\\selector_events.py\", line 120, in _read_from_self\n",
      "    data = self._ssock.recv(4096)\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    }
   ],
   "source": [
    "len(text), len(summary)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "superb-monroe",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
